#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_



#include <driver/gpio.h>
#define ML307_TX_PIN GPIO_NUM_7
#define ML307_RX_PIN GPIO_NUM_8    
#define ML307_RST_PIN GPIO_NUM_42
#define ADC_PA_PIN GPIO_NUM_41
#define CHRG_PIN GPIO_NUM_2

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_21
#define AUDIO_I2S_GPIO_WS GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_13
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_48
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_17
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_40
#define POWER_KEY_GPIO          GPIO_NUM_10
#define BOOT_BUTTON_GPIO        GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_15
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_16

#define BUILTIN_LED_GPIO1        GPIO_NUM_4
#define BUILTIN_LED_GPIO2        GPIO_NUM_5
#define BUILTIN_LED_GPIO3        GPIO_NUM_6
#endif // _BOARD_CONFIG_H_
